fail_fast: false
minimum_pre_commit_version: 2.13.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.7
    hooks:
      # fix errors
      - id: ruff
        args: [--fix]
      # format
      - id: ruff-format
